# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class fileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFiles = channel.unary_stream(
                '/fileService/SearchFiles',
                request_serializer=service__pb2.File.SerializeToString,
                response_deserializer=service__pb2.multipleFilesResponse.FromString,
                )
        self.ListAllFiles = channel.unary_stream(
                '/fileService/ListAllFiles',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.multipleFilesResponse.FromString,
                )


class fileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_fileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchFiles,
                    request_deserializer=service__pb2.File.FromString,
                    response_serializer=service__pb2.multipleFilesResponse.SerializeToString,
            ),
            'ListAllFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAllFiles,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.multipleFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class fileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fileService/SearchFiles',
            service__pb2.File.SerializeToString,
            service__pb2.multipleFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAllFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fileService/ListAllFiles',
            service__pb2.Empty.SerializeToString,
            service__pb2.multipleFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
