# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x18\n\x04\x46ile\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"E\n\x12singleFileResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0blastUpdated\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\";\n\x15multipleFilesResponse\x12\"\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x13.singleFileResponse\"\x07\n\x05\x45mpty2o\n\x0b\x66ileService\x12.\n\x0bSearchFiles\x12\x05.File\x1a\x16.multipleFilesResponse0\x01\x12\x30\n\x0cListAllFiles\x12\x06.Empty\x1a\x16.multipleFilesResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILE']._serialized_start=17
  _globals['_FILE']._serialized_end=41
  _globals['_SINGLEFILERESPONSE']._serialized_start=43
  _globals['_SINGLEFILERESPONSE']._serialized_end=112
  _globals['_MULTIPLEFILESRESPONSE']._serialized_start=114
  _globals['_MULTIPLEFILESRESPONSE']._serialized_end=173
  _globals['_EMPTY']._serialized_start=175
  _globals['_EMPTY']._serialized_end=182
  _globals['_FILESERVICE']._serialized_start=184
  _globals['_FILESERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
